[build]
  publish = "app"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/data/**/*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/shia"
  to   = "/shia.html"
  status = 200
